import type { AnswerSet } from '../src/domain/preferences.ts';

const newcomer: AnswerSet = {
  experience: ['new'],
  setup: ['ready'],
  freshness: ['balanced'],
  maintenance: ['minimal'],
  control: ['drive'],
  customization: ['touches'],
  release: ['either'],
  'system-model': ['either'],
  'use-cases': ['everyday'],
  gaming: ['none'],
  hardware: ['recent'],
  gpu: ['unknown'],
  'software-freedom': ['prefer'],
  troubleshooting: ['search'],
  identity: ['background'],
  path: ['comfortable'],
};

// Reusable local review fixtures, excluded from browser bundles.
export const preferenceExamples: Readonly<Record<string, AnswerSet>> = {
  newcomer,
  gamer: {
    ...newcomer,
    experience: ['tried'],
    freshness: ['modern'],
    'use-cases': ['everyday', 'gaming'],
    gaming: ['main'],
    hardware: ['powerful'],
    gpu: ['nvidia'],
    'system-model': ['containers'],
    identity: ['dependable'],
    path: ['modern'],
  },
  developer: {
    ...newcomer,
    experience: ['regular'],
    setup: ['little'],
    freshness: ['modern'],
    control: ['understand'],
    'use-cases': ['development', 'homelab'],
    'system-model': ['protected'],
    troubleshooting: ['investigate'],
    identity: ['dependable'],
    path: ['modern'],
  },
  tinkerer: {
    ...newcomer,
    experience: ['regular'],
    setup: ['configure'],
    freshness: ['modern'],
    maintenance: ['occasional'],
    control: ['understand'],
    customization: ['castle'],
    troubleshooting: ['investigate'],
    identity: ['shape'],
    path: ['artisan'],
  },
  architect: {
    ...newcomer,
    experience: ['terminal'],
    setup: ['configure'],
    control: ['everything'],
    'use-cases': ['development', 'learning'],
    'system-model': ['protected'],
    troubleshooting: ['learn'],
    identity: ['declarative'],
    path: ['artisan'],
  },
  oldHardware: {
    ...newcomer,
    'use-cases': ['everyday', 'old-hardware'],
    hardware: ['limited'],
    freshness: ['proven'],
    identity: ['minimal'],
  },
  securityBeginner: {
    ...newcomer,
    'use-cases': ['learning', 'security'],
    troubleshooting: ['learn'],
    path: ['forbidden'],
  },
  enthusiast: {
    ...newcomer,
    experience: ['init'],
    setup: ['build'],
    freshness: ['newest'],
    maintenance: ['hobby'],
    control: ['everything'],
    customization: ['castle'],
    release: ['rolling'],
    'system-model': ['traditional'],
    'use-cases': ['development', 'learning'],
    troubleshooting: ['learn'],
    identity: ['unix'],
    path: ['forbidden'],
  },
};
